# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'raw_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1380, 784)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list_groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.list_groupbox.setObjectName("list_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.list_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.categories_list = QtWidgets.QListView(self.list_groupbox)
        self.categories_list.setMaximumSize(QtCore.QSize(16777215, 250))
        self.categories_list.setObjectName("categories_list")
        self.verticalLayout.addWidget(self.categories_list)
        self.item_list = QtWidgets.QListWidget(self.list_groupbox)
        self.item_list.setObjectName("item_list")
        self.verticalLayout.addWidget(self.item_list)
        self.horizontalLayout.addWidget(self.list_groupbox)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.details_tab = QtWidgets.QWidget()
        self.details_tab.setObjectName("details_tab")
        self.tabWidget.addTab(self.details_tab, "")
        self.documents_tab = QtWidgets.QWidget()
        self.documents_tab.setObjectName("documents_tab")
        self.tabWidget.addTab(self.documents_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1380, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.list_groupbox.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.details_tab), _translate("MainWindow", "Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.documents_tab), _translate("MainWindow", "Documents"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
